name: almizaj_client_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  shared_preferences: ^2.5.4
  google_fonts: ^8.0.2
  font_awesome_flutter: ^10.12.0
  carousel_slider: ^5.1.2
  shimmer: ^3.0.0
  provider: ^6.1.5+1
  flutter_localizations:
    sdk: flutter
  badges: ^3.1.2
  web: ^0.5.1
  lottie: ^3.3.2
  flutter_animate: ^4.5.2
  sensors_plus: ^7.0.0
  confetti: ^0.8.0
  fl_chart: ^1.1.1
  local_auth: ^3.0.1
  speech_to_text: ^6.6.2
  geolocator: ^12.0.0
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true